version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 19
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      -  $(aws ecr get-login --no-include-email --region us-east-2)
    
  build:
    commands:
      - echo "Entered build phase"
      - echo "Building Java"
      - ls
      - cd tweetauthenticationservice
      - ls
      - mvn compile
      - mvn package -DskipTests
      - echo " building docker image"
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
      - docker build -t tweetuirepo .
      - docker tag tweetuirepo:latest 330935856020.dkr.ecr.us-east-2.amazonaws.com/tweetuirepo:latest
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - echo "Pushing Docker Image"
      - docker push 330935856020.dkr.ecr.us-east-2.amazonaws.com/tweetuirepo:latest
      - echo writing deifinition file
      - printf '[{"name":"tweetUiClusterUpdate ","imageUri":"%s"}]'330935856020.dkr.ecr.us-east-2.amazonaws.com/tweetuirepo:latest>taskdefination.json
artifacts:
  files:
    - tweetuirepo/taskdefinition.json
